### ISSUE TITLE
Build errors in 5.3

### ISSUE THREAD

**Issue by x157** [fpwong/BlueprintAssistWiki#141]
I'm using a custom 5.3 engine.  I migrated BlueprintAssist from 5.2 release to 5.3.  During the migration it compiles correctly, though there is a warning.

After migration, any time I try to compile a Project using this Engine, or the Engine itself, it tries to recompile BlueprintAssist.  When it does, it gets errors.

Here is the relevant part of the error log:

```
11>Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
11>  Executing up to 24 processes, one per physical core
11>------ Building 75 action(s) started ------
11>[1/75] Compile [x64] BlueprintAssistGraphHandler.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[2/75] Compile [x64] BlueprintAssistGraphActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[3/75] Compile [x64] BlueprintAssistToolbar_BlueprintImpl.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[4/75] Compile [x64] BlueprintAssistTabActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[5/75] Compile [x64] BlueprintAssistTabHandler.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[6/75] Compile [x64] BlueprintAssistCommentContainsGraph.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[7/75] Compile [x64] LinkPinMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[8/75] Compile [x64] BlueprintAssist.init.gen.cpp
11>[9/75] Compile [x64] BlueprintAssistCommentHandler.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[10/75] Compile [x64] BlueprintAssistGlobals.cpp
11>[11/75] Compile [x64] BlueprintAssistUtils.gen.cpp
11>[12/75] Compile [x64] BlueprintAssistSettings_Advanced.cpp
11>[13/75] Compile [x64] BARootObject.cpp
11>[14/75] Compile [x64] BlueprintAssistSettings_Advanced.gen.cpp
11>[15/75] Compile [x64] BAMiscUtils.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistUtils\BAMiscUtils.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistObjects/BAAssetEditorHandlerObject.h': No such file or directory
11>[16/75] Compile [x64] BlueprintAssistSettings_EditorFeatures.cpp
11>[17/75] Compile [x64] BlueprintAssistGraphCommands.cpp
11>[18/75] Compile [x64] BlueprintAssistToolkitActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistActions\BlueprintAssistToolkitActions.cpp(6): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[19/75] Compile [x64] BABlueprintActionMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[20/75] Compile [x64] BlueprintAssistStyle.cpp
11>[21/75] Compile [x64] BlueprintAssistToolbar.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[22/75] Compile [x64] BlueprintAssistGraphOverlay.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[23/75] Compile [x64] BlueprintAssistNodeActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[24/75] Compile [x64] GraphFormatterTypes.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[25/75] Compile [x64] KnotTrackCreator.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[26/75] Compile [x64] BlueprintAssistSettings.gen.cpp
11>[27/75] Compile [x64] BlueprintAssistActionsBase.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[28/75] Compile [x64] GoToSymbolMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[29/75] Compile [x64] EdGraphFormatter.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[30/75] Compile [x64] BlueprintAssistGraphPanelNodeFactory.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphPanelNodeFactory.cpp(7): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistWidgets/BlueprintAssistKnotNode.h': No such file or directory
11>[31/75] Compile [x64] BlueprintAssistPinActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[32/75] Compile [x64] BlueprintAssistHotkeyMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistInputProcessor.h(9): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistActions/BlueprintAssistBlueprintActions.h': No such file or directory
11>[33/75] Compile [x64] SBASizeProgress.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[34/75] Compile [x64] BlueprintAssistSettings.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[35/75] Compile [x64] KnotTrack.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[36/75] Compile [x64] BlueprintAssistGlobalActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistActions\BlueprintAssistGlobalActions.cpp(6): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[37/75] Compile [x64] BlueprintAssistUtils.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[38/75] Compile [x64] FocusSearchBoxMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[39/75] Compile [x64] BlueprintAssistNodeSizeChangeData.cpp
11>[40/75] Compile [x64] BlueprintAssistBlueprintActions.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistActions\BlueprintAssistBlueprintActions.cpp(6): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[41/75] Compile [x64] BADebugMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\BADebugMenu.cpp(4): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[42/75] Compile [x64] AddSymbolMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[43/75] Compile [x64] BABlueprintHandlerObject.gen.cpp
11>[44/75] Compile [x64] VariableSelectorMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\VariableSelectorMenu.cpp(12): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[45/75] Compile [x64] BlueprintAssistEditorFeatures.gen.cpp
11>[46/75] Compile [x64] BlueprintAssistDelayedDelegate.cpp
11>[47/75] Compile [x64] BehaviorTreeGraphFormatter.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[48/75] Compile [x64] SimpleFormatter.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[49/75] Compile [x64] OpenWindowMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[50/75] Compile [x64] BlueprintAssistCommands.cpp
11>[51/75] Compile [x64] BlueprintAssistCache.gen.cpp
11>[52/75] Compile [x64] BARootObject.gen.cpp
11>[53/75] Compile [x64] EditDetailsMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[54/75] Compile [x64] BlueprintAssistTypes.cpp
11>[55/75] Compile [x64] BlueprintAssistTypes.gen.cpp
11>[56/75] Compile [x64] BAAssetEditorHandlerObject.gen.cpp
11>[57/75] Compile [x64] BAFormatterUtils.cpp
11>[58/75] Compile [x64] BlueprintAssistSettings_EditorFeatures.gen.cpp
11>[59/75] Compile [x64] BAAssetEditorHandlerObject.cpp
11>[60/75] Compile [x64] BlueprintAssistGraphExtender.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[61/75] Compile [x64] BlueprintAssistWorkflowModeMenu.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\BlueprintAssistWidgets\BlueprintAssistWorkflowModeMenu.cpp(10): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistUtils/BAMiscUtils.h': No such file or directory
11>[62/75] Compile [x64] BABlueprintHandlerObject.cpp
11>[63/75] Compile [x64] BlueprintAssistInputProcessor.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistInputProcessor.h(9): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistActions/BlueprintAssistBlueprintActions.h': No such file or directory
11>[64/75] Compile [x64] BlueprintAssistModule.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistInputProcessor.h(9): fatal error C1083: Cannot open include file: 'BlueprintAssist/BlueprintAssistActions/BlueprintAssistBlueprintActions.h': No such file or directory
11>[65/75] Compile [x64] EdGraphParameterFormatter.cpp
11>E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Public\BlueprintAssistGraphHandler.h(8): fatal error C1083: Cannot open include file: 'BlueprintAssist/GraphFormatters/GraphFormatterTypes.h': No such file or directory
11>[66/75] Compile [x64] BlueprintAssistEditorFeatures.cpp
11>[67/75] Compile [x64] BlueprintAssistKnotNode.cpp
11>[68/75] Compile [x64] BlueprintAssistOpenFileMenu.cpp
11>[69/75] Compile [x64] BlueprintAssistCache.cpp
11>[70/75] Compile [x64] BlueprintAssistTabSwitcher.cpp
11>[71/75] Compile [x64] BlueprintAssistCreateAssetMenu.cpp
11>Total time in Parallel executor: 6.38 seconds
11>Total execution time: 11.87 seconds
11>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command "..\..\Build\BatchFiles\Build.bat -Target="UnrealEditor Win64 Development" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code 6.
11>Done building project "UE5.vcxproj" -- FAILED.
========== Build: 10 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 12:20 PM and took 16.889 seconds ==========
```

Here is the initial warning from the migration:

`[22/74] Compile [x64] BlueprintAssistSettings.cpp
C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistSettings.cpp(411): warning C4996: 'FMessageDialog::Open': Use the overload of Open that takes the Title by-value. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.`

This is the command I used to migrate:

```powershell
PS> MigrateUEMarketplacePlugin.ps1 -Plugin BlueprintAssist -From "E:/UE_5.2" -To "E:/XUE53" -Debug
```

Here is the full output from the migration:

```powershell
DEBUG: Copy [BlueprintAssist] From [E:/UE_5.2] To [E:/XUE53]
DEBUG: Creating temp directory: [C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599]
Building BlueprintAssist for E:/XUE53
DEBUG: EXEC: E:\XUE53\Engine\Build\BatchFiles\RunUAT.bat BuildPlugin -Plugin="E:\UE_5.2\Engine\Plugins\Marketplace\BlueprintAssist\BlueprintAssist.uplugin" -Package="C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599" -CreateSubFolder
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Building AutomationTool...
Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:17.20
Starting AutomationTool...
Parsing command line: BuildPlugin -Plugin=E:\UE_5.2\Engine\Plugins\Marketplace\BlueprintAssist\BlueprintAssist.uplugin -Package=C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599 -CreateSubFolder
Initializing script modules...
Building 31 projects (see Log 'Engine/Programs/AutomationTool/Saved/Logs/Log.txt' for more details)
 Restore...
 Build...
Build projects time: 2.56 s
Total script module initialization time: 4.18 s.
Executing commands...
Copying 182 file(s) using max 64 thread(s)
Reading plugin from C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\BlueprintAssist.uplugin...
Building plugin for host platforms: Win64
Running: E:\XUE53\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "E:\XUE53\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\HostProject.uproject" -plugin="C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\BlueprintAssist.uplugin" -noubtmakefiles -manifest="C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="E:\XUE53\Engine\Programs\AutomationTool\Saved\Logs\UBT-UnrealEditor-Win64-Development.txt"
Log file: E:\XUE53\Engine\Programs\AutomationTool\Saved\Logs\UBT-UnrealEditor-Win64-Development.txt
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\HostProject.uproject C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors
Total of 22 written
Reflection code generated for UnrealEditor in 1.2848489 seconds
Writing manifest to C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
Building UnrealEditor...
Using Visual Studio 2022 14.34.31946 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933) and Windows 10.0.22621.0 SDK (C:\Program Files (x86)\Windows Kits\10).
[Adaptive Build] Excluded from LevelSequenceEditor unity file: {{SNIP_LIST_OF_1000s_OF_FILES}}
Determining max actions to execute in parallel (24 physical cores, 32 logical cores)
  Executing up to 24 processes, one per physical core
------ Building 74 action(s) started ------
[1/74] Compile [x64] BlueprintAssist.init.gen.cpp
[2/74] Compile [x64] BlueprintAssistSettings_Advanced.gen.cpp
[3/74] Compile [x64] BlueprintAssistSettings_EditorFeatures.gen.cpp
[4/74] Compile [x64] BARootObject.gen.cpp
[5/74] Compile [x64] BABlueprintHandlerObject.gen.cpp
[6/74] Compile [x64] BlueprintAssistStyle.cpp
[7/74] Compile [x64] BlueprintAssistCommands.cpp
[8/74] Compile [x64] BAAssetEditorHandlerObject.gen.cpp
[9/74] Compile [x64] BlueprintAssistSettings.gen.cpp
[10/74] Compile [x64] BlueprintAssistTypes.cpp
[11/74] Compile [x64] BlueprintAssistEditorFeatures.gen.cpp
[12/74] Compile [x64] BlueprintAssistCache.gen.cpp
[13/74] Compile [x64] BlueprintAssistDelayedDelegate.cpp
[14/74] Compile [x64] BlueprintAssistActionsBase.cpp
[15/74] Compile [x64] BehaviorTreeGraphFormatter.cpp
[16/74] Compile [x64] BlueprintAssistBlueprintActions.cpp
[17/74] Compile [x64] BlueprintAssistTabHandler.cpp
[18/74] Compile [x64] KnotTrack.cpp
[19/74] Compile [x64] BlueprintAssistGraphPanelNodeFactory.cpp
[20/74] Compile [x64] BlueprintAssistGraphOverlay.cpp
[21/74] Compile [x64] BlueprintAssistCommentContainsGraph.cpp
[22/74] Compile [x64] BlueprintAssistSettings.cpp
C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistSettings.cpp(411): warning C4996: 'FMessageDialog::Open': Use the overload of Open that takes the Title by-value. Please update your code to the new API before upgrading to the next release, otherwise your project will no longer compile.
[23/74] Compile [x64] BlueprintAssistCommentHandler.cpp
[24/74] Compile [x64] BAFormatterUtils.cpp
[25/74] Compile [x64] BlueprintAssistTabActions.cpp
[26/74] Compile [x64] BlueprintAssistToolbar_BlueprintImpl.cpp
[27/74] Compile [x64] SBASizeProgress.cpp
[28/74] Compile [x64] BlueprintAssistUtils.gen.cpp
[29/74] Compile [x64] BlueprintAssistKnotNode.cpp
[30/74] Compile [x64] BlueprintAssistTypes.gen.cpp
[31/74] Compile [x64] EdGraphParameterFormatter.cpp
[32/74] Compile [x64] BlueprintAssistGraphCommands.cpp
[33/74] Compile [x64] BlueprintAssistUtils.cpp
[34/74] Compile [x64] BlueprintAssistCache.cpp
[35/74] Compile [x64] BlueprintAssistNodeActions.cpp
[36/74] Compile [x64] BlueprintAssistSettings_EditorFeatures.cpp
[37/74] Compile [x64] BlueprintAssistModule.cpp
[38/74] Compile [x64] BlueprintAssistEditorFeatures.cpp
[39/74] Compile [x64] FocusSearchBoxMenu.cpp
[40/74] Compile [x64] BlueprintAssistInputProcessor.cpp
[41/74] Compile [x64] EditDetailsMenu.cpp
[42/74] Compile [x64] BlueprintAssistGlobals.cpp
[43/74] Compile [x64] SimpleFormatter.cpp
[44/74] Compile [x64] BlueprintAssistNodeSizeChangeData.cpp
[45/74] Compile [x64] BAMiscUtils.cpp
[46/74] Compile [x64] BARootObject.cpp
[47/74] Compile [x64] BADebugMenu.cpp
[48/74] Compile [x64] BlueprintAssistSettings_Advanced.cpp
[49/74] Compile [x64] BlueprintAssistGraphActions.cpp
[50/74] Compile [x64] AddSymbolMenu.cpp
[51/74] Compile [x64] BAAssetEditorHandlerObject.cpp
[52/74] Compile [x64] BlueprintAssistGlobalActions.cpp
[53/74] Compile [x64] VariableSelectorMenu.cpp
[54/74] Compile [x64] BABlueprintHandlerObject.cpp
[55/74] Compile [x64] BlueprintAssistToolkitActions.cpp
[56/74] Compile [x64] BABlueprintActionMenu.cpp
[57/74] Compile [x64] BlueprintAssistGraphHandler.cpp
[58/74] Compile [x64] BlueprintAssistWorkflowModeMenu.cpp
[59/74] Compile [x64] GraphFormatterTypes.cpp
[60/74] Compile [x64] KnotTrackCreator.cpp
[61/74] Compile [x64] BlueprintAssistGraphExtender.cpp
[62/74] Compile [x64] BlueprintAssistPinActions.cpp
[63/74] Compile [x64] BlueprintAssistToolbar.cpp
[64/74] Compile [x64] BlueprintAssistHotkeyMenu.cpp
[65/74] Compile [x64] EdGraphFormatter.cpp
[66/74] Compile [x64] BlueprintAssistOpenFileMenu.cpp
[67/74] Compile [x64] BlueprintAssistCreateAssetMenu.cpp
[68/74] Compile [x64] BlueprintAssistTabSwitcher.cpp
[69/74] Compile [x64] GoToSymbolMenu.cpp
[70/74] Compile [x64] LinkPinMenu.cpp
[71/74] Compile [x64] OpenWindowMenu.cpp
[72/74] Link [x64] UnrealEditor-BlueprintAssist.lib
   Creating library C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Intermediate\Build\Win64\x64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.lib and object C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Intermediate\Build\Win64\x64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.exp
[73/74] Link [x64] UnrealEditor-BlueprintAssist.dll
   Creating library C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Intermediate\Build\Win64\x64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.sup.lib and object C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Intermediate\Build\Win64\x64\UnrealEditor\Development\BlueprintAssist\UnrealEditor-BlueprintAssist.sup.exp
[74/74] WriteMetadata UnrealEditor.target
Total time in Parallel executor: 18.64 seconds
Total execution time: 27.75 seconds
Took 27.82s to run dotnet.exe, ExitCode=0
Building plugin for target platforms: Android, IOS, Linux, LinuxArm64, TVOS, Win64
Reading filter rules from C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599\HostProject\Plugins\BlueprintAssist\Config\FilterPlugin.ini
Loading FilterPluginAndroid.ini
Loading FilterPluginIOS.ini
Loading FilterPluginLinux.ini
Loading FilterPluginLinuxArm64.ini
Loading FilterPluginTVOS.ini
Loading FilterPluginWin64.ini
BUILD SUCCESSFUL
AutomationTool executed for 0h 0m 33s
AutomationTool exiting with ExitCode=0 (Success)
DEBUG: Moving [C:\Users\xist\AppData\Local\Temp\4b81f7d6-2502-414e-ac96-5f46993ec599] to [E:\XUE53\Engine\Plugins\Marketplace\BlueprintAssist]
```

**Comment by fpwong** [comment]
Thanks for letting me know. I'm not sure why it is rebuilding when it is just a warning, perhaps there may be some setting for this?

I have fixed this warning on the source repo (also sent you an invite), let me know if this solved the constant rebuild problem.

**Comment by Terie412** [comment]
Not fixed yet. Version 5.3. Same errors to above. Fail to include files like "BlueprintAssist/GraphFormatters/GraphFormatterTypes.h"

**Comment by fpwong** [comment]
> Not fixed yet. Version 5.3. Same errors to above. Fail to include files like "BlueprintAssist/GraphFormatters/GraphFormatterTypes.h"

Sorry about this, I didn't think much of the header issues in the original issues. I'm not sure how to trigger these errors on my end. I have built the plugin for 5.3 and it is live on the marketplace so they also did not have issues with building. 

Comparing the console output when building I notice that I don't get this line regarding adaptive building: 

`[Adaptive Build] Excluded from LevelSequenceEditor unity file: {{SNIP_LIST_OF_1000s_OF_FILES}}` 

Perhaps this might be what is causing this, is there something in your `BuildConfiguration.xml` that has been changed?

---

When I build:

```
C:/Programs/Epic Games/UE_5.3\Engine/Build/BatchFiles/RunUAT.bat
BuildPlugin
-Plugin=E:/Documents/Unreal/BlueprintAssistPackaged/BlueprintAssist/BlueprintAssist.uplugin
-Package=E:/Documents/Unreal/BlueprintAssistPackaged/test_package\423\build\BA_423_53\BlueprintAssist
-CreateSubFolder
Running AutomationTool...
Using bundled DotNet SDK version: 6.0.302
Starting AutomationTool...
Parsing command line: BuildPlugin -Plugin=E:/Documents/Unreal/BlueprintAssistPackaged/BlueprintAssist/BlueprintAssist.uplugin -Package=E:/Documents/Unreal/BlueprintAssistPackaged/test_package\423\build\BA_423_53\BlueprintAssist -CreateSubFolder
Initializing script modules...
Total script module initialization time: 0.21 s.
Executing commands...
Copying 735 file(s) using max 64 thread(s)
Reading plugin from E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\Plugins\BlueprintAssist\BlueprintAssist.uplugin...
Building plugin for host platforms: Win64
Running: C:\Programs\Epic Games\UE_5.3\Engine\Binaries\ThirdParty\DotNet\6.0.302\windows\dotnet.exe "C:\Programs\Epic Games\UE_5.3\Engine\Binaries\DotNET\UnrealBuildTool\UnrealBuildTool.dll" UnrealEditor Win64 Development -Project="E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\HostProject.uproject" -plugin="E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\Plugins\BlueprintAssist\BlueprintAssist.uplugin" -noubtmakefiles -manifest="E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml" -nohotreload -log="C:\Users\fpwong\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Programs+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt"
Log file: C:\Users\fpwong\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Programs+Epic+Games+UE_5.3\UBT-UnrealEditor-Win64-Development.txt
Parsing headers for UnrealEditor
  Running Internal UnrealHeaderTool E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\HostProject.uproject E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\Intermediate\Build\Win64\UnrealEditor\Development\UnrealEditor.uhtmanifest -WarningsAsErrors -installed
Total of 22 written
Reflection code generated for UnrealEditor in 2.0429279 seconds
Writing manifest to E:\Documents\Unreal\BlueprintAssistPackaged\test_package\423\build\BA_423_53\BlueprintAssist\HostProject\Saved\Manifest-UnrealEditor-Win64-Development.xml
Building UnrealEditor...
Using Visual Studio 2022 14.35.32215 toolchain (C:\Programs\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.35.32215) and Windows 10.0.22000.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Determining max actions to execute in parallel (8 physical cores, 16 logical cores)
  Requested 2 process count multiplier: limiting max parallel actions to 16
  Requested 1.5 GB memory per action, 17.74 GB available: limiting max parallel actions to 11
```

**Comment by Terie412** [comment]
Well, I am building unreal engine from source. So here are what I done:
1. I clone engine source from github on commit id : a3cb3d8fdec1fc32f071ae7d22250f33f80b21c4. 
2. And I would like blueprint assist be a part of the engine. So I install blueprint assist on the latest official UE5.3 engine on Epic games launcher. 
3. Then I copy the plugin's folder from the latest official UE5.3 engine to the engine being to build, under the folder Engine/Plugins. 
4. Then I build the UE5 project and encounter these errors. 

I build the UE5 project successfully without blueprint assist by the way.

**Comment by Terie412** [comment]
I replace all {#include "BlueprintAssist/} with {#include ".../}, and the build succeed.

**Comment by victlee69** [comment]
please fix

**Comment by fpwong** [comment]
@qintianchen Thanks for the information. I was able to replicate the build errors by placing the plugin in the engine. The root of the problem is that these problematic files are not inside the source private / public folders. I have been meaning to change this for quite some time...

Since 5.3 just came out, I expect any updates at this time to take up to 3 weeks to be live on the marketplace. So I've invited you both to the source repo where you can get the fix @victlee69. You will simply need to pull the latest commit on the main branch. 

Please let me know if the build errors still occur!

**Comment by Terie412** [comment]
> @qintianchen Thanks for the information. I was able to replicate the build errors by placing the plugin in the engine. The root of the problem is that these problematic files are not inside the source private / public folders. I have been meaning to change this for quite some time...
> 
> Since 5.3 just came out, I expect any updates at this time to take up to 3 weeks to be live on the marketplace. So I've invited you both to the source repo where you can get the fix @victlee69. You will simply need to pull the latest commit on the main branch.
> 
> Please let me know if the build errors still occur!

It's fixed!

**Comment by victlee69** [comment]
it's fixed. thanks
