### ISSUE TITLE
[Crash] EXCEPTION_ACCESS_VIOLATION (FormatText Related?)

### ISSUE THREAD

**Issue by tshabi8** [fpwong/BlueprintAssistWiki#181]
UE: 5.1.1
Plugin Version:  4.2.14

It happens on a pretty complex bp with some FormatText and switch nodes.
Tried multiple times.

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000

UnrealEditor_BlueprintAssist!FKnotTrackCreator::CreateKnotNode() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\KnotTrackCreator.cpp:919]
UnrealEditor_BlueprintAssist!FKnotTrackCreator::CreateKnotTracks() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\KnotTrackCreator.cpp:203]
UnrealEditor_BlueprintAssist!FKnotTrackCreator::FormatKnotNodes() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\KnotTrackCreator.cpp:45]
UnrealEditor_BlueprintAssist!FEdGraphFormatter::FormatNode() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\EdGraphFormatter.cpp:330]
UnrealEditor_BlueprintAssist!FBAGraphHandler::FormatNodes() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:3308]
UnrealEditor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2562]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:468]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:53]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:100]
UnrealEditor_Slate!FSlateApplication::FinishedInputThisFrame() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:1387]
UnrealEditor!FEngineLoop::Tick() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5353]
UnrealEditor!GuardedMain() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
UnrealEditor!GuardedMainWrapper() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
UnrealEditor!LaunchWindowsStartup() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
UnrealEditor!WinMain() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Hi, I just submitted a fix for this now. Will let you know when it's live on the marketplace.

**Comment by fpwong** [comment]
Should be fixed in 4.2.18 https://github.com/fpwong/BlueprintAssistWiki/releases/tag/4.2.18

**Comment by tshabi8** [comment]
Still crashing (UE 5.1.1, Plugin 4.2.18):
Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
UnrealEditor_BlueprintAssist!FKnotTrackCreator::CreateKnotTracks() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\KnotTrackCreator.cpp:244]
UnrealEditor_BlueprintAssist!FKnotTrackCreator::FormatKnotNodes() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\KnotTrackCreator.cpp:72]
UnrealEditor_BlueprintAssist!FEdGraphFormatter::FormatNode() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistFormatters\EdGraphFormatter.cpp:330]
UnrealEditor_BlueprintAssist!FBAGraphHandler::FormatNodes() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:3320]
UnrealEditor_BlueprintAssist!FBAGraphHandler::UpdateNodesRequiringFormatting() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:2553]
UnrealEditor_BlueprintAssist!FBAGraphHandler::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistGraphHandler.cpp:468]
UnrealEditor_BlueprintAssist!FBATabHandler::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistTabHandler.cpp:53]
UnrealEditor_BlueprintAssist!FBAInputProcessor::Tick() [C:\Source\UnrealEngine5.1\Engine\Plugins\Marketplace\BlueprintAssist\Source\BlueprintAssist\Private\BlueprintAssistInputProcessor.cpp:100]
UnrealEditor_Slate!FSlateApplication::FinishedInputThisFrame() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Slate\Private\Framework\Application\SlateApplication.cpp:1387]
UnrealEditor!FEngineLoop::Tick() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:5353]
UnrealEditor!GuardedMain() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Launch.cpp:202]
UnrealEditor!GuardedMainWrapper() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:107]
UnrealEditor!LaunchWindowsStartup() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:244]
UnrealEditor!WinMain() [C:\Source\UnrealEngine5.1\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:282]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

**Comment by fpwong** [comment]
Apologies, after some testing even if I fix this nullptr crash there will still be serious issues with the formatting. Post formatting, it will end up disconnecting the wires that used to be linked.

It might take some more time but it would be better to figure out the root cause of this crash.

Some things that may help resolve / debug this issue:
* Check if `Use Knot Node Pool` is disabled (it should be disabled by default)
* Disable the function `RemoveUselessCreationNodes` from being called
  * Go to the setting in Editor Pref `Blueprint Assist Debug` and add a new string `Useless`
* If possible could you share the nodes or create a similar test case which triggers this issue?

**Comment by fpwong** [comment]
Hi @tshabi8, I pushed a fix for this in 4.2.21. Please let me know if it avoided the crash.

**Comment by tshabi8** [comment]
Yeah it's fixed now! thanks
